name: Development Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Build development Docker image
        run: docker build -f services/web/Dockerfile services/web
        # builds image
